apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

images:
  - name: quay.io/abarbaro/exporters
    newName: quay.io/abarbaro/exporters
    newTag: 7df7227708801e65472f99553d904eaf5e7619e0