{
 "title": "RHTAP dora metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_staging", "query": "prometheus" },
   { "name": "datasource_production", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Dora Metrics for RHTAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stage",
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "Values have to be intended as the global average of all clusters in stage enviroment.\n\nDeployment Frequency is referring to unique deployments (image_name/commit_hash) among all clusters in staging environments. \n"
   }
  },
  {
   "title": "Production",
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 1 },
   "options": {
    "content": "Values have to be intended as the global average of all clusters in production enviroment.\n\nDeployment Frequency is referring to unique deployments (image_name/commit_hash) among all clusters in production environments. \n\n"
   }
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 24, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "**DEPLOYMENT FREQUENCY**\n\nTracks the number of successfull deployments over time. Here is displayed as the total count in the selected time range.\n\nData here is obtained from the Openshift cluster deployments metadata. \n\n**LEAD TIME FOR CHANGE**\n\nMeasures the time it takes for a code commit to successfully make it to production.\nHere is shown the average value of all successfull deployments in the selected time range.\n\nData here is obtained from the cluster deployments and Github's commit timestamps.\n\n**Change Failure Rate**\n\nDetermines the changes that lead to failures after they reach production.\nIt is calculated by dividing the number of failed deployments in production by the total number of product deployments.\n\nData here is obtained from PagerDuty.\n\n**MEAN TIME TO RESTORE**\n\nDescribes the average time to recover from a failed deployment or an incident.\nIt is calculated by obtaining the difference in time between an incident creation time and it resolution time.\n\nData here is obtained from PagerDuty.\n\n**Untracked Deployments**\nShow the number of deployment that were not used to calculate the metrics due to missing data (usually the commit time is not obtained from Github)."
   }
  },
  {
   "title": "Lead Time for Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n    (( min by (image, commit_hash)( min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]) - on (image) group_left (commit_hash) (min by (image, commit_hash) (min_over_time(dora:committime{app!~\".*gitopsdepl.*\"}[$__range]))))))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "count(count by (image)(count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Untracked Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "count(\n    min(min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])) by (image) * 1000 unless min(min_over_time(dora:committime[$__range])) by (image) * 1000\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lead Time for Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n    (( min by (image, commit_hash)( min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]) - on (image) group_left (commit_hash) (min by (image, commit_hash) (min_over_time(dora:committime{app!~\".*gitopsdepl.*\"}[$__range]))))))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "count(count by (image)(count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Untracked Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "count(\n    min(min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])) by (image) * 1000 unless min(min_over_time(dora:committime[$__range])) by (image) * 1000\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lead Time for Change over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    (( min by (image, commit_hash)( min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]) - on (image) group_left (commit_hash) (min by (image, commit_hash) (min_over_time(dora:committime{app!~\".*gitopsdepl.*\"}[$__range]))))))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Frequency over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "count(count by (image)(count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lead Time for Change over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    (( min by (image, commit_hash)( min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]) - on (image) group_left (commit_hash) (min by (image, commit_hash) (min_over_time(dora:committime{app!~\".*gitopsdepl.*\"}[$__range]))))))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Frequency over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "count(count by (image)(count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "count( min by (app) (min_over_time(dora:failure_creation_time[$__range])) )\n/ \n( \ncount( count by (image) (count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])))\n+ \n(count(min by (image) (min_over_time(dora:deployinactive[$__range]))) OR on() vector(0))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Time to Restore",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "count( min by (app) (min_over_time(dora:failure_creation_time[$__range])) )\n/ \n( \ncount( count by (image) (count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])))\n+ \n(count(min by (image) (min_over_time(dora:deployinactive[$__range]))) OR on() vector(0))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "count( min by (app) (min_over_time(dora:failure_creation_time[$__range])) )\n/ \n( \ncount( count by (image) (count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])))\n+ \n(count(min by (image) (min_over_time(dora:deployinactive[$__range]))) OR on() vector(0))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Time to Restore",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "count( min by (app) (min_over_time(dora:failure_creation_time[$__range])) )\n/ \n( \ncount( count by (image) (count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])))\n+ \n(count(min by (image) (min_over_time(dora:deployinactive[$__range]))) OR on() vector(0))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent Go Lives",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])) by (image) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent Go Lives",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])) by (image) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}