{
 "title": "DORA Metrics for StoneSoup",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(dora:deployactive{app!~\".*gitopsdepl.*\"}, app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lead time for Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n    (( min by (app, image, commit_hash)( min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]) - on (app, image) group_left (commit_hash) (min by (app, image, commit_hash) (min_over_time(dora:committime{app!~\".*gitopsdepl.*\"}[$__range]))))))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    (( min by (app, image, commit_hash)( min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]) - on (app, image) group_left (commit_hash) (min by (app, image, commit_hash) (min_over_time(dora:committime{app!~\".*gitopsdepl.*\"}[$__range]))))))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current running deplotyments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    min by (app, image, commit_hash) (min_over_time(dora:deployactive{app!~\".*gitopsdepl.*\"}[15m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "count(count_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current running deplotyments",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "min by (app, image, commit_hash) (min_over_time(dora:deployactive{app!~\".*gitopsdepl.*\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lead Time for Change per image",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(( min by (app, image, commit_hash)( min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range]) - on (app, image) group_left (commit_hash) (min by (app, image, commit_hash) (min_over_time(dora:committime{app!~\".*gitopsdepl.*\"}[$__range]))))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lead Time for current active deployments",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (app, image, commit_hash) (min_over_time(dora:deployactive{app!~\".*gitopsdepl.*\"}[1h])) - on (app, image) group_right (commit_hash) (min by (app, image, commit_hash) (min_over_time(dora:committime{app!~\".*gitopsdepl.*\"}[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Time per image",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "min(min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])) by (app, image, commit_hash) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Untracked Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    min(min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])) by (app, image, commit_hash) * 1000 unless min(min_over_time(dora:committime[$__range])) by (app, image, commit_hash) * 1000\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "    min(min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])) by (app, image, commit_hash) * 1000 unless min(min_over_time(dora:committime[$__range])) by (app, image, commit_hash) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Time per image",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "min(min_over_time(dora:committime[$__range])) by (app, image, commit_hash) * 1000 and min(min_over_time(dora:deploytime[$__range])) by (app, image, commit_hash) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent Go-Lives",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
   "targets": [
    {
     "expr": "min(min_over_time(dora:deploytime{app!~\".*gitopsdepl.*\"}[$__range])) by (app, image, commit_hash) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics by app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lead time for Change",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\n    (( min by (app, image, commit_hash)( min_over_time(dora:deploytime{app='$app'}[$__range]) - on (app, image) group_left (commit_hash) (min by (app, image, commit_hash) (min_over_time(dora:committime{app='$app'}[$__range]))))))\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(\n    (( min by (app, image, commit_hash)( min_over_time(dora:deploytime{app='$app'}[$__range]) - on (app, image) group_left (commit_hash) (min by (app, image, commit_hash) (min_over_time(dora:committime{app='$app'}[$__range]))))))\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last active deployment",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(min_over_time(dora:deployactive{app='$app'}[$__range]))*1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deployment Frequency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count_over_time(dora:deploytime{app='$app'}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "count(count_over_time(dora:deploytime{app='$app'}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Untracked Deployments",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n    min(min_over_time(dora:deploytime{app='$app'}[$__range])) by (app, image, commit_hash) * 1000 unless min(min_over_time(dora:committime{app='$app'}[$__range])) by (app, image, commit_hash) * 1000\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lead Time for Change per image",
     "type": "table",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(( min by (app, image, commit_hash)( min_over_time(dora:deploytime{app='$app'}[$__range]) - on (app, image) group_left (commit_hash) (min by (app, image, commit_hash) (min_over_time(dora:committime{app='$app'}[$__range]))))))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commit Time history",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "min(min_over_time(dora:committime{app='$app'}[$__range])) by (app, image, commit_hash) * 1000 and min(min_over_time(dora:deploytime{app='$app'}[$__range])) by (app, image, commit_hash) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deployment history",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "min(min_over_time(dora:deploytime{app='$app'}[$__range])) by (app, image, commit_hash) * 1000",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  }
 ]
}